name: "All post-commit tests"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  build-docker-artifact:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
  build-artifact:
    needs: build-docker-artifact
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  sd-unit-tests:
    needs: build-artifact
    uses: ./.github/workflows/build-and-unit-tests.yaml
    secrets: inherit
  fd-unit-tests:
    needs: build-artifact
    uses: ./.github/workflows/fast-dispatch-build-and-unit-tests.yaml
    secrets: inherit
  profiler-regression:
    needs: build-docker-artifact
    uses: ./.github/workflows/run-profiler-regression.yaml
    with:
      build_docker: false
    secrets: inherit
  eager-package-main:
    uses: ./.github/workflows/eager-package-main.yaml
    secrets: inherit
  build-docs:
    needs: build-artifact
    uses: ./.github/workflows/docs-latest-public.yaml
    secrets: inherit
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  # We used to use this for post-commit, but we didn't have enough runners
  # to support the number of developers running this workflow
  # build-and-test-measure-perf:
  # build-and-test-measure-perf-device:
