name: "All post-commit tests"

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  produce-data:
    uses: ./.github/workflows/_produce-data.yaml
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  build-docs:
    needs: build-artifact
    uses: ./.github/workflows/docs-latest-public.yaml
    secrets: inherit
