name: "[post-commit] Fast Dispatch unit tests"

on:
  workflow_dispatch:

jobs:
  build-docker-artifact:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
  build-artifact:
    needs: build-docker-artifact
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  fd-unit-tests:
    needs: build-artifact
    uses: ./.github/workflows/fast-dispatch-build-and-unit-tests.yaml
    secrets: inherit
