name: Nightly slow dispatch tests

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 1,6 * * *"

jobs:
  build-docker-artifact:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit

  build-artifact:
    needs: build-docker-artifact
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  frequent-slow-dispatch:
    needs: build-artifact
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        arch: [grayskull, wormhole_b0]
        frequent-type: [api]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
      LOGURU_LEVEL: INFO
      TT_METAL_SLOW_DISPATCH_MODE: 1
    runs-on: model-runner-${{ matrix.arch }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - uses: ./.github/actions/load-docker-image
      - name: Ensure weka mount is active
        run: |
          sudo systemctl restart mnt-MLPerf.mount
          sudo /etc/rc.local
          ls -al /mnt/MLPerf/bit_error_tests
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_${{ matrix.arch }}
      - name: Extract files
        run: tar -xvf ttm_${{ matrix.arch }}.tar
      - uses: ./.github/actions/install-python-deps
      - uses: ./.github/actions/load-docker-image
      - name: Run frequent reg tests scripts
        timeout-minutes: 210
        run: |
          ./scripts/docker/run_docker_cmd.sh -- \
            /bin/bash -c "source python_env/bin/activate \
              source ${{ github.workspace }}/python_env/bin/activate
              && cd $TT_METAL_HOME \
              && export PYTHONPATH=$TT_METAL_HOME \
              && ./tests/scripts/run_tests.sh --tt-arch ${{ matrix.arch }} --pipeline-type frequent_${{ matrix.frequent-type }} --dispatch-mode slow"
