name: "[T3K] T3000 demo tests"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # This cron schedule runs the workflow every Saturday at 12am UTC

jobs:
  build-docker-artifact:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
    
  build-artifact:
    needs: build-docker-artifact
    uses: ./.github/workflows/build-artifact.yaml
    with:
      arch: '["wormhole_b0"]'
    secrets: inherit
  t3000-demo-tests:
    needs: build-artifact
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          {
            name: "T3000 demo tests",
            arch: wormhole_b0,
            runs-on: [arch-wormhole_b0, "config-t3000", "in-service", "runner-test", "bare-metal", "pipeline-functional"],
            cmd: './tests/scripts/run_tests.sh --tt-arch wormhole_b0 --pipeline-type demos_t3000_device --dispatch-mode ""'
          },
        ]
    name: ${{ matrix.test-group.name }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.test-group.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    environment: dev
    runs-on: ${{ matrix.test-group.runs-on }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Enable performance mode
        run: |
          sudo cpupower frequency-set -g performance
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_${{ matrix.test-group.arch }}
      - name: Extract files
        run: tar -xvf ttm_${{ matrix.test-group.arch }}.tar
      - uses: ./.github/actions/install-python-deps
      - uses: ./.github/actions/load-docker-image
      - name: Run demo regression tests
        timeout-minutes: 180
        run: |
          ./scripts/docker/run_docker_cmd.sh -- \
            /bin/bash -c "source python_env/bin/activate \
            && cd $TT_METAL_HOME \
            && export PYTHONPATH=$TT_METAL_HOME \
            && ${{ matrix.test-group.cmd }}"
      - name: Disable performance mode
        if: always()
        run: |
          sudo cpupower frequency-set -g ondemand
